export const SET_GAME_STARTED= 'SET_GAME_STARTED';
export const SET_INSTRUCTIONS_EXPANDED ='SET_INSTRUCTIONS_EXPANDED';
export const SET_GUESS ='SET_GUESS';

export const DECK ={
    FETCH_SUCCESS: "FETCH_DECK_SUCCESS",
    FETCH_ERROR: "FETCH_DECK_ERROR"
};

export const DECK_DRAW = {
    FETCH_SUCCESS: "FETCH_DRAW_CARD_SUCCESS",
    FETCH_ERROR: "FETCH_DRAW_CARD_ERROR"
};